name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'med_appt/package-lock.json'

      - name: Install dependencies
        working-directory: ./med_appt
        run: npm ci

      - name: Run tests (if configured)
        working-directory: ./med_appt
        run: |
          if grep -q '"test":' package.json; then
            npm test
          else
            echo "No test script found in package.json - skipping tests"
          fi

      - name: Build the project
        working-directory: ./med_appt
        run: npm run build