name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'med_appt/package-lock.json'  # Ensures npm cache looks in the correct subdir

      - name: Install dependencies
        working-directory: ./med_appt  # All commands now run inside `med_appt/`
        run: npm ci  # Uses `package-lock.json` for exact versions

      - name: Run tests (if any)
        working-directory: ./med_appt
        run: npm test  # Example test command (adjust as needed)

      - name: Build the project
        working-directory: ./med_appt
        run: npm run build  # Assumes `build` script exists in `package.json`